/**
  *****************************************************************************
  * @title   usart_rxtx.c
  * @author  sunw
  * @date    16 Dec 2012
  * @brief   a problem in USARTSend Function, this function is solved.
  *******************************************************************************
  */
////// The above comment is automatically generated by CoIDE ///////////////////

/* Includes ------------------------------------------------------------------*/
#include "stm32f10x_usart.h"
#include "stm32f10x_rcc.h"
#include "stm32f10x_gpio.h"
#include "misc.h"

u8 USART_CMDFLAG=0;
int i,j;
unsigned char CMD_DATABUFF[11] = {'\0'};

/* Private typedef -----------------------------------------------------------*/
/* Private define ------------------------------------------------------------*/
/* Private macro -------------------------------------------------------------*/
/* Private variables ---------------------------------------------------------*/
ErrorStatus HSEStartUpStatus;

/* Private function prototypes -----------------------------------------------*/
void NVIC_Configuration(void);
void USARTGPIO_Configuration(void);
void USART_Configuration(void);
void USART1_IRQHandler(void);
void UARTSend(unsigned char *pucBuffer, unsigned long ulCount);

/******************************************************************************/
/*            STM32F10x Peripherals Interrupt Handlers                        */
/******************************************************************************/

/**
  * @brief  This function handles USARTx global interrupt request.
  * @param  None
  * @retval None
  */

void USART3_IRQHandler(void){
    if ((USART3->SR & USART_FLAG_RXNE) != (u16)RESET){
			i = USART_ReceiveData(USART3);
			if(j == 11){
                CMD_DATABUFF[j] = i;
    			CMD_DATABUFF[j+1] = '\0';
                j = 0;
			}
			else{

				CMD_DATABUFF[j++] = i;
       			CMD_DATABUFF[j] = '\0';
       			if (CMD_DATABUFF[j-1]==';'){
       				USART_CMDFLAG=1;
       				j=0;
       			}

     		}
	}
}

/* Private functions ---------------------------------------------------------*/

/*******************************************************************************
* Function Name  : usart3_rxtx
* Description    : Print "" Hello Word "  on Hyperterminal via USART3.
* Input          : None
* Output         : None
* Return         : None
*******************************************************************************/
void usart_init(void)
{
	    unsigned char menu[] = " Hello Word !\r\n";

	    /* Enable USART1 and GPIOA clock */
	    RCC_APB2PeriphClockCmd( RCC_APB2Periph_GPIOB, ENABLE);

	    RCC_APB1PeriphClockCmd(RCC_APB1Periph_USART3, ENABLE);

	    /* NVIC Configuration */
	    NVIC_Configuration();


	    /* Configure the GPIOs */
	    USARTGPIO_Configuration();

	    /* Configure the USART1 */
	    USART_Configuration();

	    /* Enable the USART1 Receive interrupt: this interrupt is generated when the
	         USART1 receive data register is not empty */
	    USART_ITConfig(USART3, USART_IT_RXNE, ENABLE);

	    /* print welcome information */
	    // USART output test
	    UARTSend(menu, sizeof(menu));




}

/*******************************************************************************
* Function Name  : USARTGPIO_Configuration
* Description    : Configures the different GPIO ports.
* Input          : None
* Output         : None
* Return         : None
*******************************************************************************/
void USARTGPIO_Configuration(void)
{
  GPIO_InitTypeDef GPIO_InitStructure;

  /* Configure USART3 Tx (PB.10) as alternate function push-pull */
  GPIO_InitStructure.GPIO_Pin = GPIO_Pin_10;
  GPIO_InitStructure.GPIO_Mode = GPIO_Mode_AF_PP;
  GPIO_InitStructure.GPIO_Speed = GPIO_Speed_50MHz;
  GPIO_Init(GPIOB, &GPIO_InitStructure);

  /* Configure USART3 Rx (PB.11) as input floating */
  GPIO_InitStructure.GPIO_Pin = GPIO_Pin_11;
  GPIO_InitStructure.GPIO_Mode = GPIO_Mode_IN_FLOATING;
  GPIO_Init(GPIOB, &GPIO_InitStructure);
}

/*******************************************************************************
* Function Name  : USART_Configuration
* Description    : Configures the USART1.
* Input          : None
* Output         : None
* Return         : None
*******************************************************************************/
void USART_Configuration(void)
{
  USART_InitTypeDef USART_InitStructure;

/* USART1 configuration ------------------------------------------------------*/
  /* USART1 configured as follow:
        - BaudRate = 9600 baud
        - Word Length = 8 Bits
        - One Stop Bit
        - No parity
        - Hardware flow control disabled (RTS and CTS signals)
        - Receive and transmit enabled
        - USART Clock disabled
        - USART CPOL: Clock is active low
        - USART CPHA: Data is captured on the middle
        - USART LastBit: The clock pulse of the last data bit is not output to
                         the SCLK pin
  */
  USART_InitStructure.USART_BaudRate = 9600;
  USART_InitStructure.USART_WordLength = USART_WordLength_8b;
  USART_InitStructure.USART_StopBits = USART_StopBits_1;
  USART_InitStructure.USART_Parity = USART_Parity_No;
  USART_InitStructure.USART_HardwareFlowControl = USART_HardwareFlowControl_None;
  USART_InitStructure.USART_Mode = USART_Mode_Rx | USART_Mode_Tx;

  USART_Init(USART3, &USART_InitStructure);

  /* Enable USART1 */
  USART_Cmd(USART3, ENABLE);
}

/**
  * @brief  Configures the nested vectored interrupt controller.
  * @param  None
  * @retval None
  */
void NVIC_Configuration(void)
{
  NVIC_InitTypeDef NVIC_InitStructure;

  /* Enable the USARTx Interrupt */
  NVIC_InitStructure.NVIC_IRQChannel = USART3_IRQn;
  NVIC_InitStructure.NVIC_IRQChannelPreemptionPriority = 0;
  NVIC_InitStructure.NVIC_IRQChannelSubPriority = 0;
  NVIC_InitStructure.NVIC_IRQChannelCmd = ENABLE;
  NVIC_Init(&NVIC_InitStructure);
}

/*******************************************************************************
* Function Name  : UARTSend
* Description    : Send a string to the UART.
* Input          : - pucBuffer: buffers to be printed.
*                : - ulCount  : buffer's length
* Output         : None
* Return         : None
*******************************************************************************/
void UARTSend(unsigned char *pucBuffer, unsigned long ulCount)
{
    //
    // Loop while there are more characters to send.
    //
    while(ulCount--)
    {
        USART_SendData(USART3, *pucBuffer++);// Last Version USART_SendData(USART1,(uint16_t) *pucBuffer++);
        /* Loop until the end of transmission */
        while(USART_GetFlagStatus(USART3, USART_FLAG_TC) == RESET)
        {
        }
    }
}

/******************* (C) COPYRIGHT 2007 STMicroelectronics *****END OF FILE****/
