all:
	gcc main.c -o main -lm -Wall
	gcc while.c -o while -lm -Wall
	gcc for_ten.c -o for_ten -lm -Wall
	gcc every_key.c -o every_key -lm -Wall
	gcc attention.c -o attention -lm -Wall
	gcc one_attention.c -o one_attention -lm -Wall
clean:
	rm -rf main while for_ten every_key attention one_attention
